
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x1024")
window.configure(bg="#FFFFFF")


canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=1024,
    width=1024,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    0.0,
    0.0,
    1024.0,
    90.0,
    fill="#187A00",
    outline="")

canvas.create_text(
    255.0,
    17.0,
    anchor="nw",
    text="Seed Archive Find / Edit",
    fill="#E4E800",
    font=("Roboto Bold", 48 * -1)
)

canvas.create_rectangle(
    0.0,
    90.0,
    1024.0,
    1024.0,
    fill="#DADADA",
    outline="")

canvas.create_text(
    480.0,
    826.0,
    anchor="nw",
    text="Notes",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    439.0,
    701.0,
    anchor="nw",
    text="Designation",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    580.0,
    766.0,
    anchor="nw",
    text="Entrant",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    102.0,
    348.0,
    anchor="nw",
    text="Location",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    91.0,
    266.0,
    anchor="nw",
    text="Variety ID",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    512.0,
    266.0,
    anchor="nw",
    text="Variety Name",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    606.0,
    348.0,
    anchor="nw",
    text="Crop",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    56.0,
    428.0,
    anchor="nw",
    text="Source",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    553.0,
    428.0,
    anchor="nw",
    text="Year (rcv)",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    68.0,
    509.0,
    anchor="nw",
    text="Quantity (g)",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    575.0,
    509.0,
    anchor="nw",
    text="Germ %",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    108.0,
    590.0,
    anchor="nw",
    text="TKW (g)",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_rectangle(
    459.0,
    134.0,
    952.0,
    199.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    202.0,
    260.0,
    459.0,
    300.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    202.0,
    341.0,
    459.0,
    381.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    666.0,
    341.0,
    921.0,
    381.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    139.0,
    422.0,
    459.0,
    462.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    665.0,
    422.0,
    921.0,
    462.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    666.0,
    503.0,
    921.0,
    543.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    202.0,
    503.0,
    459.0,
    543.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    666.0,
    760.0,
    921.0,
    800.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    575.0,
    695.0,
    921.0,
    735.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    202.0,
    584.0,
    459.0,
    624.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    162.0,
    859.0,
    861.0,
    984.0,
    fill="#C4C4C4",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=202.0,
    y=134.0,
    width=192.0,
    height=65.0
)

canvas.create_rectangle(
    666.0,
    260.0,
    921.0,
    300.0,
    fill="#C4C4C4",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=162.0,
    y=735.0,
    width=221.0,
    height=65.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=683.0,
    y=582.0,
    width=221.0,
    height=42.0
)

canvas.create_rectangle(
    0.0,
    656.0,
    1024.0,
    663.0,
    fill="#868686",
    outline="")
window.resizable(False, False)
window.mainloop()
